### ISSUE TITLE
Error after automatic logout.

### ISSUE THREAD

**Issue by paulsaxe** [molssi-seamm/seamm_dashboard#92]
I left my WebBrowser on the job list page, and the next morning clicked on Jobs List in the left menu. It popped up a dialog with this error:

```DataTables warning: table id=jobs - Ajax error. For more information about this error, please see http://datatables.net/tn/7```

This is in my version where I have set the timeout to 10 hrs, but I am sure it happened before -- and was the reason I upped the timeout before my demo.

The console had this long error message:
```[2021-11-06 06:43:14,771] ERROR in app: Exception on /api/jobs [GET]
Traceback (most recent call last):
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 121, in decorator
    verify_jwt_in_request(optional, fresh, refresh, locations)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/jwt/api_jwt.py", line 106, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/jwt/api_jwt.py", line 142, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/jwt/api_jwt.py", line 177, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask/app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "/Users/psaxe/opt/miniconda3/envs/seamm-dashboard/lib/python3.9/site-packages/flask_jwt_extended/jwt_manager.py", line 112, in handle_expired_error
    return self._expired_token_callback(e.jwt_header, e.jwt_data)
TypeError: my_expired_token_callback() takes 1 positional argument but 2 were given
```

**Comment by janash** [comment]
I think I fixed this, but not sure which PR. @paulsaxe  let me know if you see it again, otherwise I will close this issue.

**Comment by paulsaxe** [comment]
Yes, it has been fixed at some point.
